- name: Install selinux packages
  package:
    name:
    - checkpolicy
    - policycoreutils-python

- name: Create temp directory for policy creation
  file:
    path: /etc/selinux/src/baculatape
    state: directory

- name: Copy baculatape type enforcement file
  copy:
    src: baculatape.te
    dest: /etc/selinux/src/baculatape/baculatape.te
  register: semodule_source

- name: Run checkmodule on baculatape.te
  command: /usr/bin/checkmodule -M -m -o baculatape.mod baculatape.te
  args:
    chdir: /etc/selinux/src/baculatape
  when: semodule_source.changed

- name: Build baculatape module
  command: /usr/bin/semodule_package -o baculatape.pp -m baculatape.mod
  args:
    chdir: /etc/selinux/src/baculatape
  when: semodule_source.changed

- name: Install baculatape module
  command: /usr/sbin/semodule -i baculatape.pp
  args:
    chdir: /etc/selinux/src/baculatape
  when: semodule_source.changed
